remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: Santhosh Senthil's Portfolio
description: Coding Portfolio for Santhosh Senthil, a sophmore Computer Science Major at Stony Brook University, in Stony Brook, New York.
